export const stickersVentus = [
  { digit: "1E18", category: "00", name: "Mickey Sticker", origin: "Ventus" },
  { digit: "1E19", category: "00", name: "Minnie Sticker", origin: "Ventus" },
  { digit: "1E1A", category: "00", name: "Huey Sticker", origin: "Ventus" },
  { digit: "1E1B", category: "00", name: "Dewey Sticker", origin: "Ventus" },
  { digit: "1E1C", category: "00", name: "Louie Sticker", origin: "Ventus" },
  { digit: "1E1D", category: "00", name: "Rainbow Sticker", origin: "Ventus" },
  { digit: "1E1E", category: "00", name: "Chip Sticker", origin: "Ventus" },
  { digit: "1E1F", category: "00", name: "Dale Sticker", origin: "Ventus" },
  { digit: "1E20", category: "00", name: "Fireworks Sticker", origin: "Ventus" },
  { digit: "1E21", category: "00", name: "Fireworks Sticker", origin: "Ventus" },
  { digit: "1E22", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E23", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E24", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E25", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E26", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E27", category: "00", name: "Ice Cream Sticker", origin: "Ventus" },
  { digit: "1E28", category: "00", name: "Balloon Sticker", origin: "Ventus" },
  { digit: "1E29", category: "00", name: "UFO Sticker", origin: "Ventus" },
  { digit: "1E2A", category: "00", name: "Confetti Sticker", origin: "Ventus" },
  { digit: "1E2B", category: "00", name: "Confetti Sticker", origin: "Ventus" },
];