export const stickersTerra = [
  { digit: "1E36", category: "00", name: "Pete Sticker", origin: "Terra" },
  { digit: "1E37", category: "00", name: "Huey Sticker", origin: "Terra" },
  { digit: "1E38", category: "00", name: "Dewey Sticker", origin: "Terra" },
  { digit: "1E39", category: "00", name: "Louie Sticker", origin: "Terra" },
  { digit: "1E3A", category: "00", name: "Rainbow Sticker", origin: "Terra" },
  { digit: "1E3B", category: "00", name: "Airplane Sticker", origin: "Terra" },
  { digit: "1E3C", category: "00", name: "Chip Sticker", origin: "Terra" },
  { digit: "1E3D", category: "00", name: "Dale Sticker", origin: "Terra" },
  { digit: "1E3E", category: "00", name: "Flying Balloon Sticker", origin: "Terra" },
  { digit: "1E3F", category: "00", name: "Flying Balloon Sticker", origin: "Terra" },
  { digit: "1E40", category: "00", name: "Flying Balloon Sticker", origin: "Terra" },
  { digit: "1E41", category: "00", name: "Flying Balloon Sticker", origin: "Terra" },
  { digit: "1E42", category: "00", name: "Balloon Sticker", origin: "Terra" },
  { digit: "1E43", category: "00", name: "Balloon Sticker", origin: "Terra" },
  { digit: "1E44", category: "00", name: "Traffic Cone Sticker", origin: "Terra" },
  { digit: "1E45", category: "00", name: "Traffic Cone Sticker", origin: "Terra" },
  { digit: "1E46", category: "00", name: "Traffic Cone Sticker", origin: "Terra" },
  { digit: "1E47", category: "00", name: "Balloon Sticker", origin: "Terra" },
  { digit: "1E48", category: "00", name: "Balloon Sticker", origin: "Terra" },
  { digit: "1E49", category: "00", name: "UFO Sticker", origin: "Terra" },
];
