export const stickersAqua = [
  { digit: "1E54", category: "00", name: "Minnie Sticker", origin: "Aqua" },
  { digit: "1E55", category: "00", name: "Daisy Sticker", origin: "Aqua" },
  { digit: "1E56", category: "00", name: "Donald Sticker", origin: "Aqua" },
  { digit: "1E57", category: "00", name: "Horace Sticker", origin: "Aqua" },
  { digit: "1E58", category: "00", name: "Fireworks Sticker", origin: "Aqua" },
  { digit: "1E59", category: "00", name: "Rainbow Sticker", origin: "Aqua" },
  { digit: "1E5A", category: "00", name: "Chip Sticker", origin: "Aqua" },
  { digit: "1E5B", category: "00", name: "Dale Sticker", origin: "Aqua" },
  { digit: "1E5C", category: "00", name: "Fireworks Sticker", origin: "Aqua" },
  { digit: "1E5D", category: "00", name: "Fireworks Sticker", origin: "Aqua" },
  { digit: "1E5E", category: "00", name: "UFO Sticker", origin: "Aqua" },
  { digit: "1E5F", category: "00", name: "Picnic Basket Sticker", origin: "Aqua" },
  { digit: "1E60", category: "00", name: "Juice Sticker", origin: "Aqua" },
  { digit: "1E61", category: "00", name: "Donut Sticker", origin: "Aqua" },
  { digit: "1E62", category: "00", name: "Flower Sticker", origin: "Aqua" },
  { digit: "1E63", category: "00", name: "Flower Sticker", origin: "Aqua" },
  { digit: "1E64", category: "00", name: "Flower Sticker", origin: "Aqua" },
  { digit: "1E65", category: "00", name: "Bubble Sticker", origin: "Aqua" },
  { digit: "1E66", category: "00", name: "Bubble Sticker", origin: "Aqua" },
  { digit: "1E67", category: "00", name: "Bubble Sticker", origin: "Aqua" },
];
