export const ventusRadiant = [
  { address: "D72EAE", name: "Soothing Crystal", prefix: "6" },
  { address: "D72EB6", name: "Pulsing Crystal", prefix: "6" },
  { address: "D72EBE", name: "Ether", prefix: "6" },
  { address: "D72EC6", name: "Potion", prefix: "6" },
  { address: "D72ECE", name: "Panacea", prefix: "6" },
  { address: "D72ED6", name: "Fira", prefix: "6" },
  { address: "D72EDE", name: "Hi-Potion", prefix: "6" },
  { address: "D72EE6", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "D72EA6", name: "Counter Rush", prefix: "6" },
  { address: "D72F1E", name: "Block Recipe", prefix: "6" },
  { address: "D72EEE", name: "Hi-Potion", prefix: "6" },
  { address: "D72EF6", name: "Binding Strike", prefix: "6" },
  { address: "D72EFE", name: "Wellspring Crystal", prefix: "6" },
  { address: "D72F06", name: "Slow", prefix: "6" },
  { address: "D72F16", name: "Hi-Potion", prefix: "6" },
  { address: "D72F0E", name: "Freeze Raid", prefix: "6" },
];
