export const ventusNeverland = [
  { address: "D73056", name: "Megalixir", prefix: "B" },
  { address: "D7305E", name: "Mega-Potion", prefix: "B" },
  { address: "D73066", name: "Ether", prefix: "B" },
  { address: "D7306E", name: "Hi-Potion", prefix: "B" },
  { address: "D73076", name: "Firaga", prefix: "B" },
  { address: "D7307E", name: "Treasure Raid", prefix: "B" },
  { address: "D73086", name: "Aeroga", prefix: "B" },
  { address: "D7308E", name: "Blitz", prefix: "B" },
  { address: "D73096", name: "Elixir", prefix: "B" },
  { address: "D7309E", name: "Hi-Potion", prefix: "B" },
  { address: "D730A6", name: "Panacea", prefix: "B" },
  { address: "D730D6", name: "Balloon Letter", prefix: "B" },
  { address: "D730AE", name: "Mega-Ether", prefix: "B" },
  { address: "D730B6", name: "Fleeting Crystal", prefix: "B" },
  { address: "D730BE", name: "Map (Neverland)", prefix: "B" },
  { address: "D730C6", name: "Abounding Crystal", prefix: "B" },
  { address: "D730CE", name: "Megalixir", prefix: "B" },
];
