export const ventusDisney = [
  { address: "D72F4E", name: "Map (Disney Town)", prefix: "C" },
  { address: "D72F56", name: "Potion", prefix: "C" },
  { address: "D72F26", name: "Superglide", prefix: "C" },
  { address: "D72F2E", name: "Reversal Slash", prefix: "C" },
  { address: "D72F36", name: "Slot Edge", prefix: "C" },
  { address: "D72F3E", name: "Shimmering Crystal", prefix: "C" },
  { address: "D72F46", name: "Stop", prefix: "C" },
  { address: "D72F5E", name: "Mega-Ether", prefix: "C" },
  { address: "D72F66", name: "Mega-Potion", prefix: "C" },
  { address: "D72F6E", name: "Chaos Crystal", prefix: "C" },
  { address: "D72F76", name: "Thunder", prefix: "C" },
  { address: "D72F7E", name: "Thunder", prefix: "C" },
  { address: "D72F96", name: "Mega-Potion", prefix: "C" },
  { address: "D72F86", name: "Panacea", prefix: "C" },
  { address: "D72FAE", name: "Action Recipe", prefix: "C" },
  { address: "D72F8E", name: "Aerial Slam", prefix: "C" },
  { address: "D72F9E", name: "Break Time", prefix: "C" },
  { address: "D72FA6", name: "Wellspring Crystal", prefix: "C" },
];
