export const ventusEnchanted = [
  { address: "D72E16", name: "Balloon Letter", prefix: "4" },
  { address: "D72E1E", name: "Soothing Crystal", prefix: "4" },
  { address: "D72E26", name: "Cure", prefix: "4" },
  { address: "D72E2E", name: "Wellspring Crystal", prefix: "4" },
  { address: "D72E9E", name: "Absolute Zero", prefix: "4" },
  { address: "D72E0E", name: "Hi-Potion", prefix: "4" },
  { address: "D72E36", name: "Fleeting Crystal", prefix: "4" },
  { address: "D72E3E", name: "Tornado Strike", prefix: "4" },
  { address: "D72E4E", name: "Wellspring Crystal", prefix: "4" },
  { address: "D72E5E", name: "Hungry Crystal", prefix: "4" },
  { address: "D72E76", name: "Magnet", prefix: "4" },
  { address: "D72E96", name: "Hi-Potion", prefix: "4" },
  { address: "D72E46", name: "Ether", prefix: "4" },
  { address: "D72E56", name: "Potion", prefix: "4" },
  { address: "D72E66", name: "Map (Enchanted Dominion)", prefix: "4" },
  { address: "D72E6E", name: "Hi-Potion", prefix: "4" },
  { address: "D72E7E", name: "Thunder", prefix: "4" },
  { address: "D72E86", name: "Hi-Potion", prefix: "4" },
  { address: "D72E8E", name: "Sleep", prefix: "4" },
];
