export const commandsVentus = [
  { digit: "0067", category: "01", name: "Treasure Raid", origin: "Ventus" },
  { digit: "0068", category: "01", name: "Spark Raid", origin: "Ventus" },
  { digit: "0069", category: "01", name: "Wind Raid", origin: "Ventus" },
  { digit: "006F", category: "01", name: "Ars Arcanum", origin: "Ventus" },
  { digit: "0070", category: "01", name: "Time Splicer", origin: "Ventus" },
  { digit: "0079", category: "01", name: "Tornado Strike", origin: "Ventus" },
  { digit: "007C", category: "01", name: "Salvation", origin: "Ventus" },
  { digit: "00A6", category: "01", name: "Faith", origin: "Ventus" },
  { digit: "00AE", category: "01", name: "Tornado", origin: "Ventus" },
  { digit: "005B", category: "01", name: "Quick Blitz", origin: "Ventus" },
  { digit: "005C", category: "01", name: "Blitz", origin: "Ventus" },
  { digit: "005F", category: "01", name: "Sliding Dash", origin: "Ventus" },
  { digit: "0060", category: "01", name: "Fire Dash", origin: "Ventus" },
  { digit: "0062", category: "01", name: "Sonic Blade", origin: "Ventus" },
  { digit: "0065", category: "01", name: "Strike Raid", origin: "Ventus" },
  { digit: "0066", category: "01", name: "Freeze Raid", origin: "Ventus" },
  { digit: "006A", category: "01", name: "Fire Surge", origin: "Ventus" },
  { digit: "006C", category: "01", name: "Thunder Surge", origin: "Ventus" },
  { digit: "006D", category: "01", name: "Aerial Slam", origin: "Ventus" },
  { digit: "0071", category: "01", name: "Poison Edge", origin: "Ventus" },
  { digit: "0073", category: "01", name: "Blizzard Edge", origin: "Ventus" },
  { digit: "0074", category: "01", name: "Stun Edge", origin: "Ventus" },
  { digit: "0075", category: "01", name: "Slot Edge", origin: "Ventus" },
  { digit: "0076", category: "01", name: "Fire Strike", origin: "Ventus" },
  { digit: "0077", category: "01", name: "Confusion Strike", origin: "Ventus" },
  { digit: "0078", category: "01", name: "Binding Strike", origin: "Ventus" },
  { digit: "007B", category: "01", name: "Magnet Spiral", origin: "Ventus" },
  { digit: "0082", category: "01", name: "Break Time", origin: "Ventus" },
  { digit: "0083", category: "01", name: "Fire", origin: "Ventus" },
  { digit: "0084", category: "01", name: "Fira", origin: "Ventus" },
  { digit: "0085", category: "01", name: "Firaga", origin: "Ventus" },
  { digit: "0087", category: "01", name: "Fission Firaga", origin: "Ventus" },
  { digit: "0089", category: "01", name: "Crawling Fire", origin: "Ventus" },
  { digit: "008A", category: "01", name: "Blizzard", origin: "Ventus" },
  { digit: "008B", category: "01", name: "Blizzara", origin: "Ventus" },
  { digit: "008C", category: "01", name: "Blizzaga", origin: "Ventus" },
  { digit: "008E", category: "01", name: "Thunder", origin: "Ventus" },
  { digit: "008F", category: "01", name: "Thundara", origin: "Ventus" },
  { digit: "0090", category: "01", name: "Thundaga", origin: "Ventus" },
  { digit: "0092", category: "01", name: "Cure", origin: "Ventus" },
  { digit: "0093", category: "01", name: "Cura", origin: "Ventus" },
  { digit: "0094", category: "01", name: "Curaga", origin: "Ventus" },
  { digit: "0095", category: "01", name: "Esuna", origin: "Ventus" },
  { digit: "0096", category: "01", name: "Mine Shield", origin: "Ventus" },
  { digit: "0097", category: "01", name: "Mine Square", origin: "Ventus" },
  { digit: "0099", category: "01", name: "Zero Gravity", origin: "Ventus" },
  { digit: "009A", category: "01", name: "Zero Gravira", origin: "Ventus" },
  { digit: "009B", category: "01", name: "Zero Graviga", origin: "Ventus" },
  { digit: "009C", category: "01", name: "Magnet", origin: "Ventus" },
  { digit: "009D", category: "01", name: "Magnera", origin: "Ventus" },
  { digit: "009E", category: "01", name: "Magnega", origin: "Ventus" },
  { digit: "00A2", category: "01", name: "Aero", origin: "Ventus" },
  { digit: "00A3", category: "01", name: "Aerora", origin: "Ventus" },
  { digit: "00A4", category: "01", name: "Aeroga", origin: "Ventus" },
  { digit: "00A7", category: "01", name: "Deep Freeze", origin: "Ventus" },
  { digit: "00B0", category: "01", name: "Transcendence", origin: "Ventus" },
  { digit: "00B1", category: "01", name: "Mini", origin: "Ventus" },
  { digit: "00B2", category: "01", name: "Blackout", origin: "Ventus" },
  { digit: "00B3", category: "01", name: "Ignite", origin: "Ventus" },
  { digit: "00B4", category: "01", name: "Confuse", origin: "Ventus" },
  { digit: "00B5", category: "01", name: "Bind", origin: "Ventus" },
  { digit: "00B6", category: "01", name: "Poison", origin: "Ventus" },
  { digit: "00B7", category: "01", name: "Slow", origin: "Ventus" },
  { digit: "00B8", category: "01", name: "Stop", origin: "Ventus" },
  { digit: "00B9", category: "01", name: "Stopra", origin: "Ventus" },
  { digit: "00BA", category: "01", name: "Stopga", origin: "Ventus" },
  { digit: "00BB", category: "01", name: "Sleep", origin: "Ventus" },
  { digit: "00D3", category: "01", name: "Group Cure", origin: "Ventus" },
  { digit: "00D4", category: "01", name: "Group Cura", origin: "Ventus" },
  { digit: "00D5", category: "01", name: "Group Curaga", origin: "Ventus" },
  { digit: "00D6", category: "01", name: "Group Esuna", origin: "Ventus" },
  { digit: "00D7", category: "01", name: "Confetti", origin: "Ventus" },
  { digit: "00D8", category: "01", name: "Fireworks", origin: "Ventus" },
  { digit: "00D9", category: "01", name: "Taunt", origin: "Ventus" },
  { digit: "00DA", category: "01", name: "Victory Pose", origin: "Ventus" },
  { digit: "00DC", category: "01", name: "Vanish", origin: "Ventus" },
  { digit: "00DD", category: "01", name: "Unison Rush", origin: "Ventus" },
  { digit: "00DE", category: "01", name: "Voltage Stack", origin: "Ventus" },
  { digit: "00DF", category: "01", name: "Trinity Limit", origin: "Ventus" },
  { digit: "00F2", category: "01", name: "Illusion-F", origin: "Ventus" },
  { digit: "00F3", category: "01", name: "Illusion-L", origin: "Ventus" },
  { digit: "00F4", category: "01", name: "Illusion-V", origin: "Ventus" },
  { digit: "00F5", category: "01", name: "Illusion-R", origin: "Ventus" },
  { digit: "00F6", category: "01", name: "Illusion-B", origin: "Ventus" },
];
