export const commandsAqua = [
  { digit: "005D", category: "01", name: "Magic Hour", origin: "Aqua" },
  { digit: "006B", category: "01", name: "Barrier Surge", origin: "Aqua" },
  { digit: "0070", category: "01", name: "Time Splicer", origin: "Aqua" },
  { digit: "0072", category: "01", name: "Wishing Edge", origin: "Aqua" },
  { digit: "0088", category: "01", name: "Triple Firaga", origin: "Aqua" },
  { digit: "008D", category: "01", name: "Triple Blizzaga", origin: "Aqua" },
  { digit: "0091", category: "01", name: "Thundaga Shot", origin: "Aqua" },
  { digit: "0098", category: "01", name: "Seeker Mine", origin: "Aqua" },
  { digit: "009F", category: "01", name: "Munny Magnet", origin: "Aqua" },
  { digit: "00A0", category: "01", name: "Energy Magnet", origin: "Aqua" },
  { digit: "00A1", category: "01", name: "D-Link Magnet", origin: "Aqua" },
  { digit: "00A8", category: "01", name: "Glacier", origin: "Aqua" },
  { digit: "00A9", category: "01", name: "Ice Barrage", origin: "Aqua" },
  { digit: "00AA", category: "01", name: "Firaga Burst", origin: "Aqua" },
  { digit: "00AB", category: "01", name: "Raging Storm", origin: "Aqua" },
  { digit: "005B", category: "01", name: "Quick Blitz", origin: "Aqua" },
  { digit: "005C", category: "01", name: "Blitz", origin: "Aqua" },
  { digit: "005F", category: "01", name: "Sliding Dash", origin: "Aqua" },
  { digit: "0060", category: "01", name: "Fire Dash", origin: "Aqua" },
  { digit: "0062", category: "01", name: "Sonic Blade", origin: "Aqua" },
  { digit: "0065", category: "01", name: "Strike Raid", origin: "Aqua" },
  { digit: "0066", category: "01", name: "Freeze Raid", origin: "Aqua" },
  { digit: "006A", category: "01", name: "Fire Surge", origin: "Aqua" },
  { digit: "006C", category: "01", name: "Thunder Surge", origin: "Aqua" },
  { digit: "006D", category: "01", name: "Aerial Slam", origin: "Aqua" },
  { digit: "0071", category: "01", name: "Poison Edge", origin: "Aqua" },
  { digit: "0073", category: "01", name: "Blizzard Edge", origin: "Aqua" },
  { digit: "0074", category: "01", name: "Stun Edge", origin: "Aqua" },
  { digit: "0075", category: "01", name: "Slot Edge", origin: "Aqua" },
  { digit: "0076", category: "01", name: "Fire Strike", origin: "Aqua" },
  { digit: "0077", category: "01", name: "Confusion Strike", origin: "Aqua" },
  { digit: "0078", category: "01", name: "Binding Strike", origin: "Aqua" },
  { digit: "007B", category: "01", name: "Magnet Spiral", origin: "Aqua" },
  { digit: "0082", category: "01", name: "Break Time", origin: "Aqua" },
  { digit: "0083", category: "01", name: "Fire", origin: "Aqua" },
  { digit: "0084", category: "01", name: "Fira", origin: "Aqua" },
  { digit: "0085", category: "01", name: "Firaga", origin: "Aqua" },
  { digit: "0087", category: "01", name: "Fission Firaga", origin: "Aqua" },
  { digit: "0089", category: "01", name: "Crawling Fire", origin: "Aqua" },
  { digit: "008A", category: "01", name: "Blizzard", origin: "Aqua" },
  { digit: "008B", category: "01", name: "Blizzara", origin: "Aqua" },
  { digit: "008C", category: "01", name: "Blizzaga", origin: "Aqua" },
  { digit: "008E", category: "01", name: "Thunder", origin: "Aqua" },
  { digit: "008F", category: "01", name: "Thundara", origin: "Aqua" },
  { digit: "0090", category: "01", name: "Thundaga", origin: "Aqua" },
  { digit: "0092", category: "01", name: "Cure", origin: "Aqua" },
  { digit: "0093", category: "01", name: "Cura", origin: "Aqua" },
  { digit: "0094", category: "01", name: "Curaga", origin: "Aqua" },
  { digit: "0095", category: "01", name: "Esuna", origin: "Aqua" },
  { digit: "0096", category: "01", name: "Mine Shield", origin: "Aqua" },
  { digit: "0097", category: "01", name: "Mine Square", origin: "Aqua" },
  { digit: "0099", category: "01", name: "Zero Gravity", origin: "Aqua" },
  { digit: "009A", category: "01", name: "Zero Gravira", origin: "Aqua" },
  { digit: "009B", category: "01", name: "Zero Graviga", origin: "Aqua" },
  { digit: "009C", category: "01", name: "Magnet", origin: "Aqua" },
  { digit: "009D", category: "01", name: "Magnera", origin: "Aqua" },
  { digit: "009E", category: "01", name: "Magnega", origin: "Aqua" },
  { digit: "00A2", category: "01", name: "Aero", origin: "Aqua" },
  { digit: "00A3", category: "01", name: "Aerora", origin: "Aqua" },
  { digit: "00A4", category: "01", name: "Aeroga", origin: "Aqua" },
  { digit: "00A7", category: "01", name: "Deep Freeze", origin: "Aqua" },
  { digit: "00B0", category: "01", name: "Transcendence", origin: "Aqua" },
  { digit: "00B1", category: "01", name: "Mini", origin: "Aqua" },
  { digit: "00B2", category: "01", name: "Blackout", origin: "Aqua" },
  { digit: "00B3", category: "01", name: "Ignite", origin: "Aqua" },
  { digit: "00B4", category: "01", name: "Confuse", origin: "Aqua" },
  { digit: "00B5", category: "01", name: "Bind", origin: "Aqua" },
  { digit: "00B6", category: "01", name: "Poison", origin: "Aqua" },
  { digit: "00B7", category: "01", name: "Slow", origin: "Aqua" },
  { digit: "00B8", category: "01", name: "Stop", origin: "Aqua" },
  { digit: "00B9", category: "01", name: "Stopra", origin: "Aqua" },
  { digit: "00BA", category: "01", name: "Stopga", origin: "Aqua" },
  { digit: "00BB", category: "01", name: "Sleep", origin: "Aqua" },
  { digit: "00D3", category: "01", name: "Group Cure", origin: "Aqua" },
  { digit: "00D4", category: "01", name: "Group Cura", origin: "Aqua" },
  { digit: "00D5", category: "01", name: "Group Curaga", origin: "Aqua" },
  { digit: "00D6", category: "01", name: "Group Esuna", origin: "Aqua" },
  { digit: "00D7", category: "01", name: "Confetti", origin: "Aqua" },
  { digit: "00D8", category: "01", name: "Fireworks", origin: "Aqua" },
  { digit: "00D9", category: "01", name: "Taunt", origin: "Aqua" },
  { digit: "00DA", category: "01", name: "Victory Pose", origin: "Aqua" },
  { digit: "00DC", category: "01", name: "Vanish", origin: "Aqua" },
  { digit: "00DD", category: "01", name: "Unison Rush", origin: "Aqua" },
  { digit: "00DE", category: "01", name: "Voltage Stack", origin: "Aqua" },
  { digit: "00DF", category: "01", name: "Trinity Limit", origin: "Aqua" },
  { digit: "00F2", category: "01", name: "Illusion-F", origin: "Aqua" },
  { digit: "00F3", category: "01", name: "Illusion-L", origin: "Aqua" },
  { digit: "00F4", category: "01", name: "Illusion-V", origin: "Aqua" },
  { digit: "00F5", category: "01", name: "Illusion-R", origin: "Aqua" },
  { digit: "00F6", category: "01", name: "Illusion-B", origin: "Aqua" },
];
