export const actionVentus = [
  { digit: "00FB", category: "01", name: "Dodge Roll", origin: "Ventus" },
  { digit: "00FC", category: "01", name: "Thunder Roll", origin: "Ventus" },
  { digit: "0101", category: "01", name: "Reversal", origin: "Ventus" },
  { digit: "0102", category: "01", name: "Glide", origin: "Ventus" },
  { digit: "0103", category: "01", name: "Superglide", origin: "Ventus" },
  { digit: "0104", category: "01", name: "Fire Glide", origin: "Ventus" },
  { digit: "0105", category: "01", name: "Homing Slide", origin: "Ventus" },
  { digit: "0109", category: "01", name: "Teleport", origin: "Ventus" },
  { digit: "010A", category: "01", name: "Renewal Block", origin: "Ventus" },
  { digit: "010B", category: "01", name: "Focus Block", origin: "Ventus" },
  { digit: "010C", category: "01", name: "Stun Block", origin: "Ventus" },
  { digit: "010D", category: "01", name: "Poison Block", origin: "Ventus" },
  { digit: "0113", category: "01", name: "Counter Rush", origin: "Ventus" },
  { digit: "0115", category: "01", name: "Reversal Slash", origin: "Ventus" },
  { digit: "0117", category: "01", name: "Payback Raid", origin: "Ventus" },
  { digit: "00FA", category: "01", name: "High Jump", origin: "Ventus" },
  { digit: "00FF", category: "01", name: "Air Slide", origin: "Ventus" },
  { digit: "0100", category: "01", name: "Ice Slide", origin: "Ventus" },
  { digit: "011A", category: "01", name: "Aerial Recovery", origin: "Ventus" },
];
