export const terraSpace = [
  { address: "D72C4E", name: "High Jump", prefix: "9" },
  { address: "D72C86", name: "Brutal Blast", prefix: "9" },
  { address: "D72C8E", name: "Pulsing Crystal", prefix: "9" },
  { address: "D72C96", name: "Mega-Ether", prefix: "9" },
  { address: "D72CAE", name: "Mega-Potion", prefix: "9" },
  { address: "D72CBE", name: "Map (Deep Space)", prefix: "9" },
  { address: "D72C56", name: "Hi-Potion", prefix: "9" },
  { address: "D72C5E", name: "Ether", prefix: "9" },
  { address: "D72C66", name: "Hi-Potion", prefix: "9" },
  { address: "D72C6E", name: "Pulsing Crystal", prefix: "9" },
  { address: "D72C76", name: "Warp", prefix: "9" },
  { address: "D72C7E", name: "Hi-Potion", prefix: "9" },
  { address: "D72C9E", name: "Hungry Crystal", prefix: "9" },
  { address: "D72CD6", name: "Mega-Potion", prefix: "9" },
  { address: "D72CDE", name: "Fleeting Crystal", prefix: "9" },
  { address: "D72CB6", name: "Thundara", prefix: "9" },
  { address: "D72CC6", name: "Abounding Crystal", prefix: "9" },
  { address: "D72CCE", name: "Wellspring Crystal", prefix: "9" },
  { address: "D72CA6", name: "Mine Square", prefix: "9" },
];
