export const terraRadiant = [
  { address: "D72B56", name: "Fira", prefix: "6" },
  { address: "D72B5E", name: "Pulsing Crystal", prefix: "6" },
  { address: "D72B66", name: "Potion", prefix: "6" },
  { address: "D72B6E", name: "Hi-Potion", prefix: "6" },
  { address: "D72B3E", name: "Esuna", prefix: "6" },
  { address: "D72B46", name: "Blackout", prefix: "6" },
  { address: "D72B4E", name: "Hi-Potion", prefix: "6" },
  { address: "D72B86", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "D72B9E", name: "Panacea", prefix: "6" },
  { address: "D72B8E", name: "Thunder Surge", prefix: "6" },
  { address: "D72B96", name: "Fleeting Crystal", prefix: "6" },
  { address: "D72BA6", name: "Shimmering Crystal", prefix: "6" },
  { address: "D72B76", name: "Mega-Potion", prefix: "6" },
  { address: "D72B7E", name: "Chaos Crystal", prefix: "6" },
];
