export const terraNeverland = [
  { address: "D72CEE", name: "Hi-Potion", prefix: "B" },
  { address: "D72CF6", name: "Ether", prefix: "B" },
  { address: "D72CFE", name: "Hi-Potion", prefix: "B" },
  { address: "D72D06", name: "Mega-Potion", prefix: "B" },
  { address: "D72D0E", name: "Firaga", prefix: "B" },
  { address: "D72D16", name: "Dark Haze", prefix: "B" },
  { address: "D72D1E", name: "Geo Impact", prefix: "B" },
  { address: "D72D26", name: "Elixir", prefix: "B" },
  { address: "D72D7E", name: "Hi-Potion", prefix: "B" },
  { address: "D72D2E", name: "Shimmering Crystal", prefix: "B" },
  { address: "D72D36", name: "Mega Magic Recipe", prefix: "B" },
  { address: "D72CE6", name: "Map (Neverland)", prefix: "B" },
  { address: "D72D3E", name: "Hi-Potion", prefix: "B" },
  { address: "D72D6E", name: "Megalixir", prefix: "B" },
  { address: "D72D76", name: "Zero Graviga", prefix: "B" },
  { address: "D72D46", name: "Abounding Crystal", prefix: "B" },
  { address: "D72D4E", name: "Panacea", prefix: "B" },
  { address: "D72D56", name: "Megalixir", prefix: "B" },
  { address: "D72D5E", name: "Ars Solum", prefix: "B" },
  { address: "D72D66", name: "Chaos Crystal", prefix: "B" },
];
