export const keybladesVentus = [
  { digit: "0001", category: "00", name: "Wayward Wind", origin: "Ventus" },
  { digit: "0002", category: "00", name: "Treasure Trove", origin: "Ventus" },
  { digit: "0003", category: "00", name: "Stroke of Midnight", origin: "Ventus" },
  { digit: "0004", category: "00", name: "Fairy Stars", origin: "Ventus" },
  { digit: "0005", category: "00", name: "Victory Line", origin: "Ventus" },
  { digit: "0006", category: "00", name: "Mark of a Hero", origin: "Ventus" },
  { digit: "0007", category: "00", name: "Hyperdrive", origin: "Ventus" },
  { digit: "0008", category: "00", name: "Pixie Petal", origin: "Ventus" },
  { digit: "0009", category: "00", name: "Ultima Weapon", origin: "Ventus" },
  { digit: "000A", category: "00", name: "Sweetstack", origin: "Ventus" },
  { digit: "000D", category: "00", name: "Frolic Flame", origin: "Ventus" },
  { digit: "000E", category: "00", name: "Lost Memory", origin: "Ventus" },
  { digit: "0010", category: "00", name: "Void Gear", origin: "Ventus" },
  { digit: "0011", category: "00", name: "No Name", origin: "Ventus" },
  { digit: "0012", category: "00", name: "Royal Radiance", origin: "Ventus" },
];
