export const keybladesAqua = [
  { digit: "0200", category: "00", name: "Rainfell", origin: "Aqua" },
  { digit: "0201", category: "00", name: "Treasure Trove", origin: "Aqua" },
  { digit: "0202", category: "00", name: "Stroke of Midnight", origin: "Aqua" },
  { digit: "0203", category: "00", name: "Fairy Stars", origin: "Aqua" },
  { digit: "0204", category: "00", name: "Victory Line", origin: "Aqua" },
  { digit: "0205", category: "00", name: "Mark of a Hero", origin: "Aqua" },
  { digit: "0206", category: "00", name: "Hyperdrive", origin: "Aqua" },
  { digit: "0207", category: "00", name: "Pixie Petal", origin: "Aqua" },
  { digit: "0208", category: "00", name: "Ultima Weapon", origin: "Aqua" },
  { digit: "0209", category: "00", name: "Sweetstack", origin: "Aqua" },
  { digit: "020A", category: "00", name: "Destiny's Embrace", origin: "Aqua" },
  { digit: "020B", category: "00", name: "Stormfall", origin: "Aqua" },
  { digit: "020C", category: "00", name: "Brightcrest", origin: "Aqua" },
  { digit: "0210", category: "00", name: "Void Gear", origin: "Aqua" },
  { digit: "0211", category: "00", name: "No Name", origin: "Aqua" },
  { digit: "0212", category: "00", name: "Royal Radiance", origin: "Aqua" },
  { digit: "0213", category: "00", name: "Master's Defender", origin: "Aqua" },
];
