const dlinkAbilitySlots = [
  { address: "8155D4", name: "Ventus Haste", prefix: "" },
  { address: "8155D6", name: "Ventus Auto-Counter", prefix: "" },
  { address: "8155D8", name: "Aqua Magic Deflector", prefix: "" },
  { address: "8155DA", name: "Aqua Auto-Life", prefix: "" },
  { address: "8155DC", name: "Terra Overdrive", prefix: "" },
  { address: "8155DE", name: "Terra Auto-Block", prefix: "" },
  { address: "8155E0", name: "Mickey Auto-Teleport", prefix: "" },
  { address: "8155E2", name: "Mickey Double EXP", prefix: "" },
  { address: "8155E4", name: "Donald Magic Boost", prefix: "" },
  { address: "8155E6", name: "Donald Shell", prefix: "" },
  { address: "8155E8", name: "Goofy Protect", prefix: "" },
  { address: "8155EA", name: "Goofy Stun Boost", prefix: "" },
  { address: "8155EC", name: "Snow White Gauge Boost", prefix: "" },
  { address: "8155EE", name: "Snow White Quick Reload", prefix: "" },
  { address: "8155F0", name: "Cinderella Auto-Remedy", prefix: "" },
  { address: "8155F2", name: "Cinderella Regen", prefix: "" },
  { address: "8155F4", name: "Maleficent Focus Saver", prefix: "" },
  { address: "8155F6", name: "Maleficent Drain", prefix: "" },
  { address: "8155F8", name: "Zack Berserk", prefix: "" },
  { address: "8155FA", name: "Zack Attack Deflector", prefix: "" },
  { address: "8155FC", name: "Stitch Attack Boost", prefix: "" },
  { address: "8155FE", name: "Stitch Double CP", prefix: "" },
  { address: "815600", name: "Peter Pan Float", prefix: "" },
  { address: "815602", name: "Peter Pan Double Strike", prefix: "" },
  { address: "815604", name: "Pete Munny Plus", prefix: "" },
  { address: "815606", name: "Pete Steal", prefix: "" },
];

export const dlinkAbilityLocations = [...dlinkAbilitySlots];
