export const aquaRadiant = [
  { address: "D72F56", name: "Potion", prefix: "6" },
  { address: "D72F5E", name: "Ether", prefix: "6" },
  { address: "D72F66", name: "Hi-Potion", prefix: "6" },
  { address: "D72F6E", name: "Thundara", prefix: "6" },
  { address: "D72F76", name: "Hi-Potion", prefix: "6" },
  { address: "D72FA6", name: "Block Recipe", prefix: "6" },
  { address: "D72F4E", name: "Counter Blast", prefix: "6" },
  { address: "D72FAE", name: "Soothing Crystal", prefix: "6" },
  { address: "D72FC6", name: "Xehanort's Report 3", prefix: "6" },
  { address: "D72F7E", name: "Zero Gravity", prefix: "6" },
  { address: "D72F86", name: "Wellspring Crystal", prefix: "6" },
  { address: "D72F8E", name: "Strike Raid", prefix: "6" },
  { address: "D72F96", name: "Fleeting Crystal", prefix: "6" },
  { address: "D72F9E", name: "Map (Radiant Garden)", prefix: "6" },
  { address: "D72FBE", name: "Panacea", prefix: "6" },
  { address: "D72FB6", name: "Mine Square", prefix: "6" },
];
