export const aquaDwarf = [
  { address: "D72E5E", name: "Balloon Letter", prefix: "2" },
  { address: "D72E66", name: "Potion", prefix: "2" },
  { address: "D72E6E", name: "Shimmering Crystal", prefix: "2" },
  { address: "D72E76", name: "Magnet", prefix: "2" },
  { address: "D72E7E", name: "Shimmering Crystal", prefix: "2" },
  { address: "D72E86", name: "Fleeting Crystal", prefix: "2" },
  { address: "D72E8E", name: "Fire", prefix: "2" },
  { address: "D72E96", name: "Fission Firaga", prefix: "2" },
  { address: "D72E9E", name: "Potion", prefix: "2" },
  { address: "D72EAE", name: "Map (Dwarf Woodlands)", prefix: "2" },
  { address: "D72ECE", name: "Fleeting Crystal", prefix: "2" },
  { address: "D72EA6", name: "Hungry Crystal", prefix: "2" },
  { address: "D72EB6", name: "Hi-Potion", prefix: "2" },
  { address: "D72EBE", name: "Ether", prefix: "2" },
  { address: "D72EC6", name: "Potion", prefix: "2" },
  { address: "D72E4E", name: "Payback Surge", prefix: "2" },
  { address: "D72E56", name: "Poison", prefix: "2" },
  { address: "D72ED6", name: "Attack Recipe", prefix: "2" },
];
