export const aquaDisney = [
  { address: "D72FCE", name: "Map (Disney Town)", prefix: "C" },
  { address: "D72FD6", name: "Potion", prefix: "C" },
  { address: "D72FDE", name: "Abouding Crystal", prefix: "C" },
  { address: "D72FE6", name: "Fira", prefix: "C" },
  { address: "D72FEE", name: "Slot Edge", prefix: "C" },
  { address: "D72FF6", name: "Hungry Crystal", prefix: "C" },
  { address: "D72FFE", name: "Mega-Potion", prefix: "C" },
  { address: "D73006", name: "Chaos Crystal", prefix: "C" },
  { address: "D7300E", name: "Thunder", prefix: "C" },
  { address: "D73016", name: "Thunder", prefix: "C" },
  { address: "D73046", name: "Pulsing Crystal", prefix: "C" },
  { address: "D7302E", name: "Mega-Potion", prefix: "C" },
  { address: "D7301E", name: "Panacea", prefix: "C" },
  { address: "D7304E", name: "Action Recipe", prefix: "C" },
  { address: "D73026", name: "Aerial Slam", prefix: "C" },
  { address: "D73036", name: "Break Time", prefix: "C" },
  { address: "D7303E", name: "Soothing Crystal", prefix: "C" },
];
