export const aquaNeverland = [
  { address: "D730E6", name: "Firaga Burst", prefix: "B" },
  { address: "D730EE", name: "Elixir", prefix: "B" },
  { address: "D730F6", name: "Hi-Potion", prefix: "B" },
  { address: "D730FE", name: "Ether", prefix: "B" },
  { address: "D73146", name: "Hi-Potion", prefix: "B" },
  { address: "D73106", name: "Mine Shield", prefix: "B" },
  { address: "D7310E", name: "Elixir", prefix: "B" },
  { address: "D73116", name: "Map (Neverland)", prefix: "B" },
  { address: "D7311E", name: "Mega-Potion", prefix: "B" },
  { address: "D73126", name: "Panacea", prefix: "B" },
  { address: "D7314E", name: "Fleeting Crystal", prefix: "B" },
  { address: "D7312E", name: "Time Splicer", prefix: "B" },
  { address: "D7313E", name: "Thundaga", prefix: "B" },
  { address: "D73156", name: "Chaos Crystal", prefix: "B" },
  { address: "D7315E", name: "Firaga", prefix: "B" },
  { address: "D73136", name: "Mega-Ether", prefix: "B" },
];
