export const startingWeaponAqua = [
  { digit: "02", name: "Rainfell", origin: "Aqua" },
  { digit: "05", name: "Treasure Trove", origin: "Aqua" },
  { digit: "08", name: "Stroke of Midnight", origin: "Aqua" },
  { digit: "0B", name: "Fairy Stars", origin: "Aqua" },
  { digit: "0E", name: "Victory Line", origin: "Aqua" },
  { digit: "11", name: "Mark of a Hero", origin: "Aqua" },
  { digit: "14", name: "Hyperdrive", origin: "Aqua" },
  { digit: "17", name: "Pixie Petal", origin: "Aqua" },
  { digit: "1A", name: "Ultima Weapon", origin: "Aqua" },
  { digit: "1D", name: "Sweetstack", origin: "Aqua" },
  { digit: "23", name: "Destiny's Embrace", origin: "Aqua" },
  { digit: "24", name: "Stormfall", origin: "Aqua" },
  { digit: "25", name: "Brightcrest", origin: "Aqua" },
  { digit: "2A", name: "Void Gear", origin: "Aqua" },
  { digit: "2D", name: "No Name", origin: "Aqua" },
  { digit: "30", name: "Royal Radiance", origin: "Aqua" },
  { digit: "32", name: "Master's Defender", origin: "Aqua" },
];
