export const ingredientsTerra = [
  { digit: "4609", category: "00", name: "Bijou Bean", origin: "Terra" },
  { digit: "460A", category: "00", name: "Nutty Nut", origin: "Terra" },
  { digit: "460C", category: "00", name: "Bizzaro Bean", origin: "Terra" },
  { digit: "460E", category: "00", name: "Crystal Sugar", origin: "Terra" },
  { digit: "4615", category: "00", name: "Golden Jam", origin: "Terra" },
  { digit: "461B", category: "00", name: "Whipped Dream", origin: "Terra" },
  { digit: "4623", category: "00", name: "Galactic Caramel", origin: "Terra" },
  { digit: "462E", category: "00", name: "Starry Sky Delight", origin: "Terra" },
  { digit: "460D", category: "00", name: "Gaspberry", origin: "Terra" },
  { digit: "4614", category: "00", name: "Rose Honey", origin: "Terra" },
  { digit: "4629", category: "00", name: "Nebula Cracker", origin: "Terra" },
  { digit: "462A", category: "00", name: "Birthday Cake", origin: "Terra" },
  { digit: "4600", category: "00", name: "Dancin' Lemon", origin: "Terra" },
  { digit: "4607", category: "00", name: "Melodious Grape", origin: "Terra" },
  { digit: "4608", category: "00", name: "Open Sesame", origin: "Terra" },
  { digit: "4610", category: "00", name: "Prickle Pepper", origin: "Terra" },
  { digit: "4611", category: "00", name: "Toonbasco", origin: "Terra" },
  { digit: "4612", category: "00", name: "Merry Mint", origin: "Terra" },
  { digit: "461C", category: "00", name: "Soy Milk", origin: "Terra" },
  { digit: "4620", category: "00", name: "Rocket Soda", origin: "Terra" },
  { digit: "4627", category: "00", name: "Thundercrack", origin: "Terra" },
  { digit: "462D", category: "00", name: "Rich Marshmallow", origin: "Terra" },
  { digit: "4604", category: "00", name: "Primordial Cactus", origin: "Terra" },
  { digit: "4619", category: "00", name: "Starlight Jelly", origin: "Terra" },
  { digit: "4622", category: "00", name: "Green Goo", origin: "Terra" },
  { digit: "4625", category: "00", name: "Meteor Cocoa", origin: "Terra" },
  { digit: "4626", category: "00", name: "Chocobo Chocolate", origin: "Terra" },
];
