export const ingredientsVentus = [
  { digit: "4605", category: "00", name: "Cherryberry", origin: "Ventus" },
  { digit: "4606", category: "00", name: "Apple Pie", origin: "Ventus" },
  { digit: "460B", category: "00", name: "Jumbo Almond", origin: "Ventus" },
  { digit: "4613", category: "00", name: "Honeybunch", origin: "Ventus" },
  { digit: "4616", category: "00", name: "Star Syrup", origin: "Ventus" },
  { digit: "461D", category: "00", name: "Merry Diary", origin: "Ventus" },
  { digit: "461E", category: "00", name: "Moogle Coffee", origin: "Ventus" },
  { digit: "4624", category: "00", name: "Chocolate Valentine", origin: "Ventus" },
  { digit: "462B", category: "00", name: "Wedding Cake", origin: "Ventus" },
  { digit: "462C", category: "00", name: "Forest Muffin", origin: "Ventus" },
  { digit: "4617", category: "00", name: "Rainbow Syrup", origin: "Ventus" },
  { digit: "461A", category: "00", name: "Cream Fluff", origin: "Ventus" },
  { digit: "4628", category: "00", name: "Cotton Cloudcandy", origin: "Ventus" },
  { digit: "4600", category: "00", name: "Dancin' Lemon", origin: "Ventus" },
  { digit: "4607", category: "00", name: "Melodious Grape", origin: "Ventus" },
  { digit: "4608", category: "00", name: "Open Sesame", origin: "Ventus" },
  { digit: "4610", category: "00", name: "Prickle Pepper", origin: "Ventus" },
  { digit: "4611", category: "00", name: "Toonbasco", origin: "Ventus" }, 
  { digit: "4612", category: "00", name: "Merry Mint", origin: "Ventus" },
  { digit: "461C", category: "00", name: "Soy Milk", origin: "Ventus" },
  { digit: "4620", category: "00", name: "Rocket Soda", origin: "Ventus" },
  { digit: "4627", category: "00", name: "Thundercrack", origin: "Ventus" }, 
  { digit: "462D", category: "00", name: "Rich Marshmallow", origin: "Ventus" },
  { digit: "4604", category: "00", name: "Primordial Cactus", origin: "Ventus" },
  { digit: "4619", category: "00", name: "Starlight Jelly", origin: "Ventus" },
  { digit: "4622", category: "00", name: "Green Goo", origin: "Ventus" },
  { digit: "4625", category: "00", name: "Meteor Cocoa", origin: "Ventus" },
  { digit: "4626", category: "00", name: "Chocobo Chocolate", origin: "Ventus" },
];
