export const ingredientsAqua = [
  { digit: "4601", category: "00", name: "Balloon Melon", origin: "Aqua" },
  { digit: "4602", category: "00", name: "Peach Fantasy", origin: "Aqua" },
  { digit: "4603", category: "00", name: "Heroic Orange", origin: "Aqua" },
  { digit: "460F", category: "00", name: "Mermaid Salt", origin: "Aqua" },
  { digit: "4618", category: "00", name: "Sky Blue Mousse", origin: "Aqua" },
  { digit: "461F", category: "00", name: "Crystal Soda", origin: "Aqua" },
  { digit: "4621", category: "00", name: "Fizzy Tizzy", origin: "Aqua" },
  { digit: "460D", category: "00", name: "Gaspberry", origin: "Aqua" },
  { digit: "4614", category: "00", name: "Rose Honey", origin: "Aqua" },
  { digit: "4629", category: "00", name: "Nebula Nectar", origin: "Aqua" },
  { digit: "462A", category: "00", name: "Birthday Cake", origin: "Aqua" },
  { digit: "462E", category: "00", name: "Starry Sky Delight", origin: "Aqua" },
  { digit: "4617", category: "00", name: "Rainbow Sirup", origin: "Aqua" },
  { digit: "461A", category: "00", name: "Cream Fluff", origin: "Aqua" },
  { digit: "4628", category: "00", name: "Cotton Cloudcandy", origin: "Aqua" },
  { digit: "4600", category: "00", name: "Dancin' Lemon", origin: "Aqua" },
  { digit: "4607", category: "00", name: "Melodious Grape", origin: "Aqua" },
  { digit: "4608", category: "00", name: "Open Sesame", origin: "Aqua" },
  { digit: "4610", category: "00", name: "Prickle Pepper", origin: "Aqua" },
  { digit: "4611", category: "00", name: "Toonbasco", origin: "Aqua" },
  { digit: "4612", category: "00", name: "Merry Mint", origin: "Aqua" },
  { digit: "461C", category: "00", name: "Soy Milk", origin: "Aqua" },
  { digit: "4620", category: "00", name: "Rocket Soda", origin: "Aqua" },
  { digit: "4627", category: "00", name: "Thundercrack", origin: "Aqua" },
  { digit: "462D", category: "00", name: "Rich Marshmallow", origin: "Aqua" },
  { digit: "4604", category: "00", name: "Primordial Cactus", origin: "Aqua" },
  { digit: "4619", category: "00", name: "Starlight Jelly", origin: "Aqua" },
  { digit: "4622", category: "00", name: "Green Goo", origin: "Aqua" },
  { digit: "4625", category: "00", name: "Meteor Cocoa", origin: "Aqua" },
  { digit: "4626", category: "00", name: "Chocobo Chocolate", origin: "Aqua" },
];
